from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt
from io import BytesIO

def create_word_doc(project_title: str, sections: list) -> BytesIO:
    """
    Generates a Word document from the database sections.
    """
    doc = Document()
    doc.add_heading(project_title, 0)

    sections.sort(key=lambda x: x.order_index)

    for section in sections:
        heading_text = section.heading or "Untitled Section"
        doc.add_heading(heading_text, level=1)
        
        raw_content = section.content or ""
        
        content = raw_content.replace("**", "")
        
        lines = content.split('\n')
        for line in lines:
            clean_line = line.strip()
            if clean_line.startswith('* '):
                # Add as a list item
                try:
                    doc.add_paragraph(clean_line.replace('* ', ''), style='List Bullet')
                except:
                    doc.add_paragraph(clean_line)
            elif clean_line:
                doc.add_paragraph(clean_line)

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

def create_ppt_presentation(project_title: str, sections: list) -> BytesIO:
    """
    Generates a PowerPoint.
    optimized for concise, AI-generated bullet points.
    """
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = project_title
    subtitle.text = "Generated by AI Document Platform"

    sections.sort(key=lambda x: x.order_index)

    blank_slide_layout = prs.slide_layouts[6] 

    for section in sections:
        slide = prs.slides.add_slide(blank_slide_layout)
        
        # --- 1. Add Title Box ---
        title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.4), Inches(9), Inches(1))
        title_tf = title_box.text_frame
        title_tf.text = section.heading or "Untitled Slide"
        title_tf.paragraphs[0].font.size = Pt(36)
        title_tf.paragraphs[0].font.bold = True
        title_tf.paragraphs[0].font.name = 'Arial'
        
        # --- 2. Add Content Box ---
        content_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(9), Inches(5.5))
        tf = content_box.text_frame
        tf.word_wrap = True
        
        raw_content = section.content or ""
        clean_content = raw_content.replace("**", "") 
        tf.text = clean_content

        text_len = len(clean_content)
        
        if text_len < 200:
            font_size = Pt(28) # Very short text -> Big font
        elif text_len < 400:
            font_size = Pt(24) # Standard slide text size
        elif text_len < 600:
            font_size = Pt(20) # Slightly smaller
        elif text_len < 800:
            font_size = Pt(16) # Dense text
        else:
            font_size = Pt(14) # Fallback for massive text blocks

        for paragraph in tf.paragraphs:
            paragraph.font.size = font_size
            paragraph.font.name = 'Arial'
            # Add spacing between bullet points
            paragraph.space_after = Pt(10) 
            
            # Visual indentation for bullets
            if paragraph.text.strip().startswith('*'):
                paragraph.level = 0 

    buffer = BytesIO()
    prs.save(buffer)
    buffer.seek(0)
    return buffer